### ISSUE TITLE
Overhead of insert notifications

### ISSUE THREAD

**Issue by johnjohndoe** [novoda/sqlite-provider#15]
I noticed that multiple notifications are sent when [`bulkInsert`](https://github.com/novoda/SQLiteProvider/blob/master/core/src/main/java/novoda/lib/sqliteprovider/provider/SQLiteContentProvider.java#L109) is used. I figured out this because you iterating each `ContentValue` and run an individual transaction `insert` on the item.

``` java
@Override
public int bulkInsert(Uri uri, ContentValues[] values) {
    int numValues = values.length;
    SQLiteDatabase mDb = mOpenHelper.getWritableDatabase();
    mDb.beginTransactionWithListener(this);
    try {
        for (int i = 0; i < numValues; i++) {
            Uri result = insertInTransaction(uri, values[i]);
            if (result != null) {
                mNotifyChange = true;
            }
            mDb.yieldIfContendedSafely();
        }
        mDb.setTransactionSuccessful();
    } finally {
        mDb.endTransaction();
    }

    onEndTransaction();
    return numValues;
}
```

I cannot see the reason why you are using `insert` in favor of `bulkInsert`. Could you please clarify?

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
