### ISSUE TITLE
SQLiteContentProvider#bulkInsert() should return 0 in case of failure

### ISSUE THREAD

**Issue by SebastianEngel** [novoda/sqlite-provider#18]
SQLiteContentProvider#bulkInsert() does not give any indication to the caller when the transaction was not successful. Whatever happens, it returns the count of initial values, whereas it should be "The number of values that were inserted", as done by android.content.ContentProvider#bulkInsert(), which returns 0, when an exception occurred.

I experienced this behaviour when I was inserting entities which contained the same value in unique columns. Nothing was inserted, but I expected some kind of UniqueConstraintException, which would be indicated with a return value of 0.

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
