### ISSUE TITLE
Util.SQLFile parse() method is broken

### ISSUE THREAD

**Issue by vit001** [novoda/sqlite-provider#21]
The class defines a private static String STATEMENT_END_CHARACTER = ";". This will result in statements containing a line ending with ; to be broken up, resulting in SQL errors. Such statements can be for example a INSERT TRIGGER. Some other statement separator should be used, such as a zero-length line.

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
