### ISSUE TITLE
Start following gitflow branching model

### ISSUE THREAD

**Issue by stefanhoth** [novoda/sqlite-provider#31]
In the light of adding a more streamlined process (see #16) I want to recommend applying the [gitflow branching model](http://nvie.com/posts/a-successful-git-branching-model/) for this library as it makes it easy to have a living project and yet a stable environment.

**What do we need to start this?**
- Basically we'd move our development branch from master to develop. 
- Master will become our stable branch for the tested and reviewed release version. 
- All features will be developed in feature branches and then first merged into develop for integration testing.
- After proper tests we start a release which automatically creates a tag and merges the changes back to master and develop.
- No direct commits to master. Ever.

**Easy start**

To make it easier to handle the development there are some tools:
- [git flow command](https://github.com/nvie/gitflow/wiki/Installation) to extend command line git 
- [git flow for IDEA/Android Studio](https://github.com/OpherV/gitflow4idea/) :heart:
- [Atlassian's Sourcetree](http://blog.sourcetreeapp.com/2012/08/01/smart-branching-with-sourcetree-and-git-flow/) also supports git flow natively

**Possible problems?**

Maybe there are some configuration issues with sonartype and jenkins but I think that's nothing that can't be overcome.

Questions? Opinions?

**Comment by friedger** [comment]
How hard can this be?

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
