### ISSUE TITLE
Log is visible to ALL

### ISSUE THREAD

**Issue by stefanhoth** [novoda/sqlite-provider#43]
![](https://www.dropbox.com/s/v5cu7n97wh6klz3/shot_141124_171810.png?dl=1)

Yep.

**Comment by Turkey2349** [comment]
soooo should it not be visible?

**Comment by lpicanco** [comment]
Cannot put the class Log as package level, because there are classes of others packages using that.

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
