### ISSUE TITLE
is there a demon or sample  how to update  the column?

### ISSUE THREAD

**Issue by wuzhenda** [novoda/sqlite-provider#55]
modify or del ,I don't know how to,any help?

**Comment by friedger** [comment]
You should find help at stackoverflow http://stackoverflow.com/questions/tagged/android-contentprovider or https://developer.android.com/guide/topics/providers/content-provider-basics.html#Modifications?

**Comment by wuzhenda** [comment]
OK,tks,I see.

**Comment by blundell** [comment]
You would create a new file in the assets folder, and use SQL commands to do a migration of your database columns, adding, deleting etc
