### ISSUE TITLE
getDatabaseHelper(Context context) has incorrect declaration.

### ISSUE THREAD

**Issue by tseglevskiy** [novoda/sqlite-provider#57]
SQLiteContentProviderImpl has the following implementation of getDatabaseHelper():

```
@Override
protected SQLiteOpenHelper getDatabaseHelper(Context context) {
    try {
        return new ExtendedSQLiteOpenHelper(context, getCursorFactory());
    } catch (IOException e) {
        Log.Provider.e(e);
        throw new IllegalStateException(e.getMessage());
    }
}
```

It looks like I can redefine this function and return my own SQLiteOpenHelper. But it doesn't work: somewhere in the lib will be casting back to ExtendedSQLiteOpenHelper:

Caused by: java.lang.ClassCastException: ru.jollydroid.app.Db cannot be cast to novoda.lib.sqliteprovider.sqlite.ExtendedSQLiteOpenHelper
at novoda.lib.sqliteprovider.provider.SQLiteContentProviderImpl.onCreate(SQLiteContentProviderImpl.java:43)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)

I think you need to split ExtendedSQLiteOpenHelper to two classes. One with common helper functions like getColumns() and getTables, and one with implementation of your helper.

**Comment by friedger** [comment]
In addition, two instances of ExtendedSQLiteOpenHelper are created.
