### ISSUE TITLE
Slow Method could be improved

### ISSUE THREAD

**Issue by blundell** [novoda/sqlite-provider#58]
![screen shot 2016-01-26 at 9 00 01 pm](https://cloud.githubusercontent.com/assets/655860/12594813/dc3b28a4-c46f-11e5-8e11-289f3061d2f9.png)

(recommended 0.32ms)

**Comment by xrigau** [comment]
where does that recommended time come from?

**Comment by blundell** [comment]
I have no idea what reference they have for that. Isn't it the time before jank?

**Comment by xrigau** [comment]
could be the time ignoring GC
¯\\_(ツ)_/¯

**Comment by blundell** [comment]
Using (Timing Logger)[http://developer.android.com/reference/android/util/TimingLogger.html] we determined this is the line that causes the slow down for this
 
`String[] sqls = assets.list(migrationsPath);` (Migrations:121)

The issue only arises when you have a certain number of migration files (device dependent) 10_ migration files in our case.

Considering alternative solutions, we can't speed up `assets.list` as it is a framework class.
We could move all `assets` to `res/xml` as these would be compiled and the name references would be available instantly, however this is a breaking api change and not being considered right now. 
We could also allow the library user to pass the number of the file wanting to be used so that this lookup is not needed. However this might not be possible due to the creation time and also it defeats half the point of having the migration file (vs the normal version number declaration).

So right now this is a **WILL NOT FIX**.

**Comment by blundell** [comment]
[[selfie-0 uploading...]]

**Comment by ouchadam** [comment]
is the beef that this on working on the main thread?

**Comment by blundell** [comment]
yeah, don't think it can be backgrounded ... it's instantiating the content provider
