### ISSUE TITLE
Foreign keys not working

### ISSUE THREAD

**Issue by danybony** [novoda/sqlite-provider#71]
The `ON DELETE CASCADE` statement is not respected for foreign keys.
I created the `foreign_keys` branch with a modified version of the `demo-simple` project to show this.
For a quick example, given the following DB definition
```
CREATE TABLE 'city'(
    city_id INTEGER PRIMARY KEY,
    name TEXT
);
CREATE TABLE 'shop'(
    _id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    postcode TEXT,
    city_id TEXT,
    FOREIGN KEY (city_id) REFERENCES city(city_id) ON DELETE CASCADE
);

INSERT INTO 'city'
    (city_id, name) VALUES (1, "London");
INSERT INTO 'city'
    (city_id, name) VALUES (2, "Brighton");
INSERT INTO 'shop'
    (name, postcode, city_id) VALUES ("TheBigBang Shop", "L300RA", 1);
INSERT INTO 'shop'
    (name, postcode, city_id) VALUES ("Dragons Cave", "SK85NX", 1);
INSERT INTO 'shop'
    (name, postcode, city_id) VALUES ("Firework Corner", "BN14FT", 2);
INSERT INTO 'shop'
    (name, postcode, city_id) VALUES ("Asda", "L319BH", 2);

```

When deleting the city with `city_id=1`, the relative shops are not deleted.

**Comment by Mecharyry** [comment]
```
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
            db.setForeignKeyConstraintsEnabled(true);
        }
``` 
in the `MigratingSQLiteOpenHelper.onOpen` allows foreign keys to be used and the cascade delete to work. This requires a higher android version to be used but perhaps there is an alternative workaround with the PRAGMA.

**Comment by Mecharyry** [comment]
`foreign_keys` shows a potential solution, we need to add both variations of using the above and the PRAGMA for below api level 16.

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
